# Generated by Django 4.0.4 on 2022-05-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfwh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eram',
            name='commonname',
            field=models.CharField(default=' 期', max_length=30),
        ),
        migrations.AlterField(
            model_name='genrem',
            name='genre',
            field=models.CharField(default='HistoryArt', max_length=30),
        ),
    ]
