# Generated by Django 4.0.4 on 2022-05-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfwh', '0002_eram_commonname_alter_genrem_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutm',
            name='ArtText',
            field=models.TextField(blank=True, null=True, verbose_name='art'),
        ),
        migrations.AddField(
            model_name='aboutm',
            name='MainWords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutm',
            name='textMore',
            field=models.TextField(blank=True, null=True, verbose_name='common'),
        ),
    ]
