# Generated by Django 4.0.4 on 2022-05-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfwh', '0003_aboutm_arttext_aboutm_mainwords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutm',
            name='ArtTextMore',
            field=models.TextField(blank=True, null=True, verbose_name='artcommon'),
        ),
    ]
